
import React, { useState, useMemo } from 'react';
import { Matter } from '../../types';
import { useUI } from '../../contexts/UIContext';
import { SparklesIcon, CalendarIcon, ChevronDownIcon, CalculatorIcon } from '../../constants';
import { calculateScaleIFees, calculateScaleIIFees } from '../../utils/remunerationScale';
import { formatNaira } from '../../utils/formatting';
import NairaSymbol from '../NairaSymbol';

interface AiIntakeAnalysisProps {
    matter?: Matter;
    lead?: any; // Allow lead or matter prop, normalize inside
}

export const AiIntakeAnalysis: React.FC<AiIntakeAnalysisProps> = ({ matter, lead }) => {
    const { openModal } = useUI();
    const [isExpanded, setIsExpanded] = useState(false);

    // Normalize data source (Lead or Matter)
    const analysisSource = matter?.intakeAnalysis || lead?.intakeAnalysis;
    const recordings = matter?.intakeRecordings || lead?.intakeRecordings;

    if (!analysisSource || Object.keys(analysisSource).length === 0) return null;

    const { summary, clientNextSteps, suggestedMatterTitle, applicableLaws, financialContext } = analysisSource;

    const handleScheduleConsult = () => {
        openModal('newEvent', null, {
            title: `Initial Consultation`,
            description: `Following up on AI intake analysis: ${suggestedMatterTitle || 'New Matter'}`,
            type: 'Client Meeting',
            matterId: matter?.id // Only if matter exists
        });
    };
    
    // Scale Expert Calculation
    const scaleFeeResult = useMemo(() => {
        if (!financialContext || !financialContext.estimatedValue) return null;
        
        const val = financialContext.estimatedValue;
        if (financialContext.transactionType === 'Lease') {
             return calculateScaleIIFees(val); // Default 1 year for estimation
        } else {
             return calculateScaleIFees(val);
        }
    }, [financialContext]);

    // Safety checks for arrays to prevent crashes on partial data
    const safeSteps = Array.isArray(clientNextSteps) ? clientNextSteps : [];
    const safeLaws = Array.isArray(applicableLaws) ? applicableLaws : [];
    const safeRecordings = Array.isArray(recordings) ? recordings : [];

    return (
        <div className="bg-white dark:bg-zinc-800 rounded-xl border border-purple-100 dark:border-zinc-700 overflow-hidden shadow-sm mb-6">
            <button 
                className="w-full flex items-center justify-between p-4 sm:p-6 text-left bg-gradient-to-r from-purple-50/50 to-white dark:from-zinc-800 dark:to-zinc-800"
                onClick={() => setIsExpanded(!isExpanded)}
                aria-expanded={isExpanded}
            >
                <div className="flex items-center gap-3">
                    <div className="p-2 bg-purple-100 dark:bg-purple-900/30 rounded-lg">
                        <SparklesIcon className="w-6 h-6 text-purple-600 dark:text-purple-400" />
                    </div>
                    <div>
                        <h3 className="text-lg font-bold text-slate-900 dark:text-white">Intake Intelligence</h3>
                        <p className="text-xs text-purple-600 dark:text-purple-400 font-medium">Generated by ARIA®</p>
                    </div>
                </div>
                <ChevronDownIcon className={`w-5 h-5 text-slate-400 transition-transform duration-300 ${isExpanded ? 'rotate-180' : ''}`} />
            </button>
            
            <div className={`transition-all duration-500 ease-in-out ${isExpanded ? 'max-h-[2000px] opacity-100' : 'max-h-0 opacity-0'}`}>
                <div className="p-4 sm:p-6 border-t border-slate-100 dark:border-zinc-700 space-y-6">
                    
                    {/* Summary Section */}
                    {summary && (
                        <div className="prose prose-sm dark:prose-invert max-w-none">
                            <p className="text-slate-700 dark:text-zinc-300 leading-relaxed">{summary}</p>
                        </div>
                    )}
                    
                    {/* Scale Expert Recommendation */}
                    {scaleFeeResult && financialContext && (
                        <div className="bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-500 p-4 rounded-r-lg shadow-sm">
                            <div className="flex items-center gap-2 mb-2">
                                <CalculatorIcon className="w-5 h-5 text-amber-600 dark:text-amber-400" />
                                <h4 className="font-bold text-amber-800 dark:text-amber-200 text-sm uppercase tracking-wide">Scale Expert Recommendation</h4>
                            </div>
                            <p className="text-sm text-amber-900 dark:text-amber-100 mb-2">
                                Detected Transaction: <strong>{financialContext.transactionType}</strong> of <NairaSymbol/>{formatNaira(financialContext.estimatedValue)}.
                            </p>
                            <div className="bg-white dark:bg-zinc-800 p-3 rounded border border-amber-200 dark:border-amber-800 text-sm">
                                <div className="flex justify-between items-center mb-1">
                                    <span className="text-slate-500 dark:text-zinc-400">Minimum Scale Fee ({scaleFeeResult.scale}):</span>
                                    <span className="font-bold text-lg text-slate-900 dark:text-white"><NairaSymbol/>{formatNaira(scaleFeeResult.minFee)}</span>
                                </div>
                                <p className="text-xs text-slate-400 dark:text-zinc-500 italic">
                                    "Based on the Remuneration Order 2023. Ensure your retainer or final bill does not fall below this threshold."
                                </p>
                            </div>
                        </div>
                    )}

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                        {/* Action Plan */}
                        {safeSteps.length > 0 && (
                            <div className="lg:col-span-2 bg-slate-50 dark:bg-zinc-700/30 rounded-xl p-5 border border-slate-100 dark:border-zinc-700">
                                <h4 className="font-bold text-slate-800 dark:text-white mb-4 flex items-center gap-2 text-sm">
                                    <span className="w-2 h-2 rounded-full bg-purple-500"></span>
                                    Recommended Strategy
                                </h4>
                                <ol className="space-y-4 relative border-l border-slate-200 dark:border-zinc-600 ml-2">
                                    {safeSteps.map((step, index) => (
                                        <li key={index} className="ml-4">
                                            <div className="absolute -left-1.5 mt-1.5 w-3 h-3 bg-slate-200 dark:bg-zinc-500 rounded-full border-2 border-white dark:border-zinc-800"></div>
                                            <p className="font-semibold text-sm text-slate-900 dark:text-white">{step.step}</p>
                                            <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5">{step.description}</p>
                                        </li>
                                    ))}
                                </ol>
                            </div>
                        )}

                        {/* Sidebar */}
                        <div className="space-y-4">
                             {safeLaws.length > 0 && (
                                 <div className="bg-white dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 rounded-xl p-4">
                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Relevant Laws</h4>
                                    <ul className="space-y-3">
                                        {safeLaws.map((law, index) => (
                                            <li key={index}>
                                                <p className="text-sm font-medium text-primary-600 dark:text-primary-400">{law.law}</p>
                                                <p className="text-xs text-slate-500 dark:text-zinc-400 mt-0.5 line-clamp-2">{law.summary}</p>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            )}

                            {safeRecordings.length > 0 && (
                                <div className="bg-white dark:bg-zinc-800 border border-slate-200 dark:border-zinc-700 rounded-xl p-4">
                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Source Audio</h4>
                                    <div className="space-y-2">
                                        {safeRecordings.map((rec, index) => (
                                             <audio key={index} controls src={rec.dataUrl} className="w-full h-8" />
                                        ))}
                                    </div>
                                </div>
                            )}

                             <button onClick={handleScheduleConsult} className="w-full py-2.5 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-lg font-bold text-sm hover:opacity-90 transition-opacity flex items-center justify-center gap-2 shadow-md">
                                <CalendarIcon className="w-4 h-4" />
                                Schedule Consult
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};
