/**
 * receiptDelivery — shared, type-safe builders for receipt issuance.
 *
 * WHY THIS EXISTS (the 2026-09-12 receipt failure):
 *   Both receipt paths (ServiceChargeBars auto-issue + ReceiptModal manual
 *   issue) passed `messageType: 'receipt_issued'` to the `logAutomation`
 *   Convex mutation. That mutation validates `messageType` against a
 *   strict literal union (`payment_receipt`, `rent_reminder`, …) that does
 *   NOT contain `'receipt_issued'` — Convex rejected the call, the whole
 *   try-block aborted, the receipt number was never persisted, and the UI
 *   reported failure even though the receipt HAD been delivered to the
 *   resident's portal one step earlier.
 *
 *   The `as any` casts at the component call sites let the invalid literal
 *   slip past TypeScript — so this module builds the payloads with REAL
 *   types (`AutomationMessageType`), the literals are compiler-checked, and
 *   a unit test locks the contract in place.
 */

import type { AutomationMessageType } from '../types';

/** The one valid automation-log type for a receipt issuance. */
export const RECEIPT_MESSAGE_TYPE: AutomationMessageType = 'payment_receipt';

// ─── Activity-log payload ───────────────────────────────────────────────────
export interface ReceiptLogInput {
    receiptNumber: string;
    chargeTypeLabel: string;      // "Service Charge" | "Minimum Vend"
    billingPeriod: string;        // "September 2026"
    tenantName: string;
    amountPaid: number;
    settlementMethod: string;     // "Paid On Time" | "Paid Late" | "Advance Payment"
    firmId: string;
    unitId?: string;
    senderName: string;
    senderId?: string;
    userEmail?: string;
    sessionToken?: string;
}

export interface ReceiptLogArgs {
    firmId: string;
    userEmail?: string;
    sessionToken?: string;
    unitId?: string;
    /** Compiler-checked against the backend's literal union. */
    messageType: AutomationMessageType;
    channel: 'portal';
    recipient: string;
    messagePreview: string;
    messageContent: string;
    direction: 'outbound';
    senderName: string;
    status: 'sent';
    triggeredBy?: string;
}

/**
 * Build the logAutomation payload for a receipt issuance. The messageType
 * is ALWAYS the valid `'payment_receipt'` literal — passing anything the
 * backend union rejects is now a compile error, not a runtime 500.
 */
export function buildReceiptLogArgs(input: ReceiptLogInput): ReceiptLogArgs {
    const money = `₦${Math.round(input.amountPaid).toLocaleString('en-NG')}`;
    return {
        firmId: input.firmId,
        userEmail: input.userEmail,
        sessionToken: input.sessionToken,
        unitId: input.unitId,
        messageType: RECEIPT_MESSAGE_TYPE,
        channel: 'portal',
        recipient: input.tenantName,
        messagePreview: `Receipt #${input.receiptNumber} issued to ${input.tenantName} for ${input.chargeTypeLabel} (${input.billingPeriod})`,
        messageContent: `Receipt #${input.receiptNumber} issued to ${input.tenantName} for ${input.chargeTypeLabel} (${input.billingPeriod}). Amount: ${money}. Settlement: ${input.settlementMethod}.`,
        direction: 'outbound',
        senderName: input.senderName,
        status: 'sent',
        triggeredBy: input.senderId,
    };
}

// ─── Portal message payload ─────────────────────────────────────────────────
export interface ReceiptPortalInput {
    receiptNumber: string;
    chargeTypeLabel: string;
    billingPeriod: string;
    amountPaid: number;
    paymentDate: string;          // ISO yyyy-mm-dd
    settlementMethod: string;
    /** Advance receipts say what range they cover, e.g. "Oct 2026 – Mar 2027 (6 cycles)". */
    coverageNote?: string;
    autoGenerated?: boolean;
}

/**
 * Build the resident-facing receipt message body (kept identical across
 * the auto-issue and manual-issue paths so residents see one voice).
 */
export function buildReceiptContent(input: ReceiptPortalInput): string {
    const money = `₦${Math.round(input.amountPaid).toLocaleString('en-NG')}`;
    const coverage = input.coverageNote ? `\nCovers: ${input.coverageNote}` : '';
    const closing = input.autoGenerated
        ? 'This receipt was auto-generated when your payment was logged by management.'
        : 'Please download the PDF from your portal or contact management if you need a copy.';
    return `Your ${input.chargeTypeLabel} receipt for ${input.billingPeriod} has been issued.\n\nReceipt No: ${input.receiptNumber}\nAmount Paid: ${money}\nPayment Date: ${input.paymentDate}\nSettlement: ${input.settlementMethod}${coverage}\n\n${closing}`;
}

// ─── Ledger upsert ──────────────────────────────────────────────────────────
/**
 * Set a receipt number on a stored period row — UPDATE if the row exists,
 * APPEND if it does not (the old `.map()`-only writes silently dropped the
 * receipt number whenever the mark hadn't been persisted yet).
 */
export function upsertReceiptNumber<T extends { index: number; receiptNumber?: string }>(
    periods: T[] | null | undefined,
    index: number,
    receiptNumber: string,
): T[] {
    const list = periods || [];
    let found = false;
    const next = list.map(p => {
        if (p && p.index === index) {
            found = true;
            return { ...p, receiptNumber };
        }
        return p;
    });
    if (!found) {
        next.push({ index, receiptNumber } as T);
        next.sort((a, b) => (a.index || 0) - (b.index || 0));
    }
    return next;
}
