const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/components/forms/PropertyForm.tsx');
let content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

console.log('Total lines:', lines.length);

// Lines 680-840 are index 679-839
const before = lines.slice(0, 679);
const after = lines.slice(839);

const fixed = [
`                {/* 3. Rental Details */}`,
`                {(isRental || (isSale && hasTenantsForSale)) && (`,
`                    <div className="p-4 bg-slate-50/50 dark:bg-zinc-800/30 rounded-xl border border-slate-100 dark:border-zinc-700/50 shadow-sm space-y-4 animate-fade-in">`,
`                        <div className="flex items-center gap-4 px-1">`,
`                            <div className="p-1.5 bg-primary-600 text-white rounded-lg shadow-sm ring-2 ring-primary-500/10">`,
`                                <CalendarIcon className="w-3.5 h-3.5" />`,
`                            </div>`,
`                            <div>`,
`                                <p className="text-[10px] font-bold text-primary-600/70 uppercase tracking-widest leading-none mb-0.5">Rental Details</p>`,
`                                <h3 className="text-base font-black text-slate-800 dark:text-white tracking-tight">Lease &amp; Rent Configuration</h3>`,
`                            </div>`,
`                        </div>`,
`                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 px-1">`,
`                            <div className="space-y-2 group">`,
`                                <label className={labelClass}>Occupancy Status</label>`,
`                                <select value={status} onChange={e => setStatus(e.target.value as Property['status'])} className={\`\${commonInputClass} !bg-white dark:!bg-zinc-900 border border-slate-200 dark:border-zinc-700\`}>`,
`                                    <option value="Occupied">Occupied</option>`,
`                                    <option value="Vacant">Vacant</option>`,
`                                    <option value="Listed">Listed on Market</option>`,
`                                    <option value="Maintenance">Under Maintenance</option>`,
`                                    <option value="Sold">Sold</option>`,
`                                </select>`,
`                            </div>`,
`                            <div className="space-y-2 group">`,
`                                <label className={labelClass}>Property Description</label>`,
`                                <input autoComplete="off" data-lpignore="true" type="text" value={description} onChange={e => setDescription(e.target.value)} className={\`\${commonInputClass} !bg-white dark:!bg-zinc-900 border border-slate-200 dark:border-zinc-700\`} placeholder="e.g. 4-Bedroom Maisonette with BQ" />`,
`                            </div>`,
`                        </div>`,
`                        <div className={\`space-y-4 pt-1 transition-all duration-300 \${status !== 'Occupied' ? 'opacity-40 grayscale pointer-events-none select-none' : 'opacity-100'}\`}>`,
`                            {unitsData.length > 1 && (`,
`                                <div className="flex flex-wrap gap-2 px-1 mb-2">`,
`                                    {unitsData.map((unit, index) => (`,
`                                        <button key={unit.id} type="button" onClick={() => setActiveUnitIndex(index)} className={\`px-4 py-1.5 rounded-xl text-xs font-bold transition-all shadow-sm border \${activeUnitIndex === index ? 'bg-primary-600 text-white border-primary-600 shadow-primary-500/20' : 'bg-white dark:bg-zinc-900 border-slate-200 dark:border-zinc-700 text-slate-500 dark:text-zinc-400 hover:border-primary-300 dark:hover:border-primary-700/50 hover:bg-primary-50/50 dark:hover:bg-primary-900/10'}\`}>`,
`                                            {unit.unitName}`,
`                                        </button>`,
`                                    ))}`,
`                                </div>`,
`                            )}`,
`                            <div className="space-y-4 pt-1 animate-fade-in" key={activeUnitIndex}>`,
`                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Rent Amount (<NairaSymbol />)</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="text" value={formatNumberWithCommas(unitsData[activeUnitIndex].rentAmount)} onChange={e => updateUnit(activeUnitIndex, 'rentAmount', parseFormattedNumber(e.target.value))} className={commonInputClass} placeholder="0.00" />`,
`                                    </div>`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Rent Frequency</label>`,
`                                        <select value={unitsData[activeUnitIndex].rentFrequency} onChange={e => updateUnit(activeUnitIndex, 'rentFrequency', e.target.value)} className={commonInputClass}>`,
`                                            <option value="Annually">Per Annum</option>`,
`                                            <option value="Bi-Annually">Bi-Annually</option>`,
`                                            <option value="Quarterly">Quarterly</option>`,
`                                            <option value="Monthly">Monthly</option>`,
`                                        </select>`,
`                                    </div>`,
`                                </div>`,
`                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Tenant Name</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="text" value={unitsData[activeUnitIndex].tenantName} onChange={e => updateUnit(activeUnitIndex, 'tenantName', e.target.value)} className={commonInputClass} placeholder="Full Name / Representative" />`,
`                                    </div>`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Tenant Phone</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="tel" value={unitsData[activeUnitIndex].tenantPhone} onChange={e => updateUnit(activeUnitIndex, 'tenantPhone', e.target.value)} className={commonInputClass} placeholder="+234..." />`,
`                                    </div>`,
`                                </div>`,
`                                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Lease Start</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="date" value={unitsData[activeUnitIndex].leaseStart} onChange={e => updateUnit(activeUnitIndex, 'leaseStart', e.target.value)} className={commonInputClass} />`,
`                                    </div>`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Tenancy Period</label>`,
`                                        <select className={commonInputClass} value={unitsData[activeUnitIndex].tenancyPeriod || ''} onChange={e => updateUnit(activeUnitIndex, 'tenancyPeriod', e.target.value)}>`,
`                                            <option value="">Manual Entry</option>`,
`                                            <option value="1 Year">1 Year</option>`,
`                                            <option value="2 Years">2 Years</option>`,
`                                            <option value="3 Years">3 Years</option>`,
`                                            <option value="6 Months">6 Months</option>`,
`                                            <option value="Monthly">Monthly / Rolling</option>`,
`                                        </select>`,
`                                    </div>`,
`                                    <div className="space-y-2 group">`,
`                                        <label className={labelClass}>Lease End</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="date" value={unitsData[activeUnitIndex].leaseEnd} onChange={e => updateUnit(activeUnitIndex, 'leaseEnd', e.target.value)} className={commonInputClass} />`,
`                                    </div>`,
`                                </div>`,
`                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 items-end">`,
`                                    {activeUnitIndex === 0 && (`,
`                                        <div className="space-y-2 group">`,
`                                            <label className={labelClass}>Management Fee (%)</label>`,
`                                            <div className="flex bg-white dark:bg-zinc-800 p-1.5 rounded-xl ring-1 ring-slate-200 dark:ring-zinc-700 shadow-sm">`,
`                                                <input autoComplete="off" data-lpignore="true" type="number" value={managementFee} onChange={e => setManagementFee(parseFloat(e.target.value) || 0)} className="flex-grow bg-transparent border-none text-sm font-bold text-primary-600 focus:ring-0 placeholder:text-slate-300" max={100} placeholder="0" />`,
`                                                <span className="px-3 text-[10px] font-black text-slate-400 uppercase tracking-widest border-l border-slate-100 dark:border-zinc-700 flex items-center">%</span>`,
`                                            </div>`,
`                                        </div>`,
`                                    )}`,
`                                    <label className={\`flex items-center gap-3 p-4 bg-white dark:bg-zinc-900 rounded-2xl border border-slate-100 dark:border-zinc-800 shadow-xs cursor-pointer group hover:ring-2 hover:ring-primary-500/20 transition-all \${activeUnitIndex !== 0 ? 'md:col-start-2' : ''}\`}>`,
`                                        <input autoComplete="off" data-lpignore="true" type="checkbox" checked={unitsData[activeUnitIndex].isPeriodicReviewEnabled} onChange={e => updateUnit(activeUnitIndex, 'isPeriodicReviewEnabled', e.target.checked)} className="rounded border-slate-200 text-primary-600 focus:ring-primary-500" />`,
`                                        <span className="text-[10px] font-bold text-slate-600 dark:text-zinc-400 uppercase tracking-widest">Enable Periodic Review</span>`,
`                                    </label>`,
`                                </div>`,
`                                {unitsData[activeUnitIndex].isPeriodicReviewEnabled && (`,
`                                    <div className="p-4 bg-white dark:bg-zinc-900 rounded-2xl border border-slate-100 dark:border-zinc-800 shadow-sm animate-fade-in space-y-2 group">`,
`                                        <label className={labelClass}>Next Rent Review</label>`,
`                                        <input autoComplete="off" data-lpignore="true" type="date" value={unitsData[activeUnitIndex].nextRentReview} onChange={e => updateUnit(activeUnitIndex, 'nextRentReview', e.target.value)} className={commonInputClass} />`,
`                                    </div>`,
`                                )}`,
`                            </div>`,
`                        </div>`,
`                        {status !== 'Occupied' && (`,
`                            <div className="px-1 py-2">`,
`                                <div className="flex items-center gap-2 p-3 bg-slate-100 dark:bg-zinc-900/50 rounded-xl border border-dashed border-slate-300 dark:border-zinc-700">`,
`                                    <div className="w-2 h-2 rounded-full bg-slate-400 animate-pulse" />`,
`                                    <p className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Tenant fields disabled — property is currently {status.toLowerCase()}</p>`,
`                                </div>`,
`                            </div>`,
`                        )}`,
`                    </div>`,
`                )}`,
];

const newLines = [...before, ...fixed, ...after];
const newContent = newLines.join('\n');
fs.writeFileSync(filePath, newContent, 'utf8');
console.log('Done! New line count:', newLines.length);
