#!/usr/bin/env python3
"""
PracticePro Van Cleif Methodology Audit Report Generator
Produces a comprehensive PDF audit with TOC, palette-driven styling, and
prioritized refactor roadmap.
"""

import os
import sys
import hashlib
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm, cm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, Image, Flowable, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f4f4f3')
SECTION_BG    = colors.HexColor('#f1f1f0')
CARD_BG       = colors.HexColor('#ecece9')
TABLE_STRIPE  = colors.HexColor('#ecebea')
HEADER_FILL   = colors.HexColor('#6a634e')
COVER_BLOCK   = colors.HexColor('#766d54')
BORDER        = colors.HexColor('#cbc5b1')
ICON          = colors.HexColor('#a59050')
ACCENT        = colors.HexColor('#8b7226')
ACCENT_2      = colors.HexColor('#6c50bf')
TEXT_PRIMARY  = colors.HexColor('#252421')
TEXT_MUTED    = colors.HexColor('#797770')
SEM_SUCCESS   = colors.HexColor('#498b5f')
SEM_WARNING   = colors.HexColor('#a68542')
SEM_ERROR     = colors.HexColor('#894d47')
SEM_INFO      = colors.HexColor('#4a76a3')

# Semantic aliases for table cells
CRITICAL_BG = colors.HexColor('#f8e8e6')
HIGH_BG     = colors.HexColor('#fbf0dd')
MEDIUM_BG   = colors.HexColor('#fdf6e3')
LOW_BG      = colors.HexColor('#eef5ee')
SAFE_BG     = colors.HexColor('#eef5ee')

# ━━ Font registration ━━
FONT_DIR = '/usr/share/fonts'
def register_fonts():
    try:
        # Noto Serif SC for body, Noto Sans SC for headings
        pdfmetrics.registerFont(TTFont('NotoSerif', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
        pdfmetrics.registerFont(TTFont('NotoSerif-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
        pdfmetrics.registerFont(TTFont('NotoSans', f'{FONT_DIR}/truetype/chinese/NotoSansSC-Regular.ttf'))
        pdfmetrics.registerFont(TTFont('NotoSans-Bold', f'{FONT_DIR}/truetype/chinese/NotoSansSC-Bold.ttf'))
        # Mono for code
        pdfmetrics.registerFont(TTFont('Mono', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
        pdfmetrics.registerFont(TTFont('Mono-Bold', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono-Bold.ttf'))
    except Exception:
        # Fallback to built-in
        pass

register_fonts()

BODY_FONT = 'NotoSerif' if 'NotoSerif' in pdfmetrics.getRegisteredFontNames() else 'Times-Roman'
BODY_BOLD = 'NotoSerif-Bold' if 'NotoSerif-Bold' in pdfmetrics.getRegisteredFontNames() else 'Times-Bold'
HEAD_FONT = 'NotoSans-Bold' if 'NotoSans-Bold' in pdfmetrics.getRegisteredFontNames() else 'Helvetica-Bold'
MONO_FONT = 'Mono' if 'Mono' in pdfmetrics.getRegisteredFontNames() else 'Courier'

# ━━ Styles ━━
def make_styles():
    s = {}
    s['Title'] = ParagraphStyle('Title', fontName=HEAD_FONT, fontSize=28, leading=34,
                                 textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=4*mm)
    s['Subtitle'] = ParagraphStyle('Subtitle', fontName=BODY_FONT, fontSize=13, leading=18,
                                    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=8*mm)
    s['MetaLine'] = ParagraphStyle('MetaLine', fontName=BODY_FONT, fontSize=10, leading=14,
                                    textColor=TEXT_MUTED, alignment=TA_LEFT)
    s['H1'] = ParagraphStyle('H1', fontName=HEAD_FONT, fontSize=18, leading=24,
                              textColor=HEADER_FILL, spaceBefore=10*mm, spaceAfter=4*mm, keepWithNext=True)
    s['H2'] = ParagraphStyle('H2', fontName=HEAD_FONT, fontSize=14, leading=18,
                              textColor=TEXT_PRIMARY, spaceBefore=6*mm, spaceAfter=3*mm, keepWithNext=True)
    s['H3'] = ParagraphStyle('H3', fontName=HEAD_FONT, fontSize=11.5, leading=15,
                              textColor=ACCENT, spaceBefore=4*mm, spaceAfter=2*mm, keepWithNext=True)
    s['Body'] = ParagraphStyle('Body', fontName=BODY_FONT, fontSize=10, leading=15,
                                textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=3*mm)
    s['BodyJustify'] = ParagraphStyle('BodyJustify', fontName=BODY_FONT, fontSize=10, leading=15,
                                textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=3*mm)
    s['Bullet'] = ParagraphStyle('Bullet', fontName=BODY_FONT, fontSize=10, leading=14,
                                  textColor=TEXT_PRIMARY, leftIndent=14, bulletIndent=4, spaceAfter=2)
    s['Code'] = ParagraphStyle('Code', fontName=MONO_FONT, fontSize=8.5, leading=11.5,
                                textColor=TEXT_PRIMARY, backColor=CARD_BG, borderPadding=4,
                                leftIndent=4, rightIndent=4, spaceAfter=3*mm, spaceBefore=1*mm)
    s['Caption'] = ParagraphStyle('Caption', fontName=BODY_FONT, fontSize=8.5, leading=11,
                                   textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=1*mm, spaceAfter=4*mm, italic=True)
    s['Callout'] = ParagraphStyle('Callout', fontName=BODY_FONT, fontSize=10.5, leading=15,
                                   textColor=TEXT_PRIMARY, backColor=CARD_BG, borderPadding=8,
                                   leftIndent=8, rightIndent=8, spaceAfter=4*mm, spaceBefore=2*mm)
    s['CalloutCritical'] = ParagraphStyle('CalloutCritical', fontName=BODY_FONT, fontSize=10.5, leading=15,
                                   textColor=TEXT_PRIMARY, backColor=CRITICAL_BG, borderPadding=8,
                                   leftIndent=8, rightIndent=8, spaceAfter=4*mm, spaceBefore=2*mm)
    s['CalloutSafe'] = ParagraphStyle('CalloutSafe', fontName=BODY_FONT, fontSize=10.5, leading=15,
                                   textColor=TEXT_PRIMARY, backColor=SAFE_BG, borderPadding=8,
                                   leftIndent=8, rightIndent=8, spaceAfter=4*mm, spaceBefore=2*mm)
    s['TableHeader'] = ParagraphStyle('TableHeader', fontName=HEAD_FONT, fontSize=9, leading=12,
                                       textColor=colors.white, alignment=TA_LEFT)
    s['TableCell'] = ParagraphStyle('TableCell', fontName=BODY_FONT, fontSize=9, leading=12,
                                     textColor=TEXT_PRIMARY, alignment=TA_LEFT)
    s['TableCellSmall'] = ParagraphStyle('TableCellSmall', fontName=BODY_FONT, fontSize=8, leading=11,
                                     textColor=TEXT_PRIMARY, alignment=TA_LEFT)
    s['TableCellBold'] = ParagraphStyle('TableCellBold', fontName=HEAD_FONT, fontSize=9, leading=12,
                                     textColor=TEXT_PRIMARY, alignment=TA_LEFT)
    s['TocL0'] = ParagraphStyle('TocL0', fontName=HEAD_FONT, fontSize=11, leading=18,
                                 textColor=TEXT_PRIMARY, leftIndent=0)
    s['TocL1'] = ParagraphStyle('TocL1', fontName=BODY_FONT, fontSize=10, leading=15,
                                 textColor=TEXT_MUTED, leftIndent=14)
    return s

STYLES = make_styles()

# ━━ TOC Doc Template ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

def add_heading(text, style, level=0):
    key = f'h_{hashlib.md5(text.encode()).hexdigest()[:8]}'
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

# ━━ Page header/footer ━━
def header_footer(canv: canvas.Canvas, doc):
    canv.saveState()
    # Top accent line
    canv.setStrokeColor(BORDER)
    canv.setLineWidth(0.4)
    canv.line(20*mm, A4[1] - 14*mm, A4[0] - 20*mm, A4[1] - 14*mm)
    # Top label
    canv.setFont(BODY_FONT, 8)
    canv.setFillColor(TEXT_MUTED)
    canv.drawString(20*mm, A4[1] - 11*mm, 'PracticePro — Van Cleif Methodology Audit')
    canv.drawRightString(A4[0] - 20*mm, A4[1] - 11*mm, 'August 2026')
    # Bottom: page number
    canv.setFont(BODY_FONT, 8)
    canv.setFillColor(TEXT_MUTED)
    canv.drawCentredString(A4[0]/2, 10*mm, f'Page {doc.page}')
    canv.restoreState()

# ━━ Helpers ━━
def P(text, style='Body'):
    return Paragraph(text, STYLES[style])

def cell(text, style='TableCell'):
    return Paragraph(text, STYLES[style])

def code(text):
    # Escape & preserve whitespace via <br/>
    text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    text = text.replace(' ', '&nbsp;').replace('\n', '<br/>')
    return Paragraph(text, STYLES['Code'])

def severity_badge(level):
    color_map = {
        'CRITICAL': SEM_ERROR,
        'HIGH': SEM_WARNING,
        'MEDIUM': ACCENT,
        'LOW': TEXT_MUTED,
        'SAFE': SEM_SUCCESS,
    }
    bg_map = {
        'CRITICAL': CRITICAL_BG,
        'HIGH': HIGH_BG,
        'MEDIUM': MEDIUM_BG,
        'LOW': LOW_BG,
        'SAFE': SAFE_BG,
    }
    c = color_map.get(level, TEXT_MUTED)
    bg = bg_map.get(level, CARD_BG)
    return f'<font color="{c.hexval()}"><b>{level}</b></font>'

def styled_table(data, col_widths, header=True, stripe=True, header_bg=HEADER_FILL):
    """Build a styled table with header row + striped data rows."""
    t = Table(data, colWidths=col_widths, repeatRows=1 if header else 0)
    style_cmds = [
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('LEFTPADDING', (0,0), (-1,-1), 5),
        ('RIGHTPADDING', (0,0), (-1,-1), 5),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 0.3, BORDER),
    ]
    if header:
        style_cmds.extend([
            ('BACKGROUND', (0,0), (-1,0), header_bg),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), HEAD_FONT),
            ('FONTSIZE', (0,0), (-1,0), 9),
            ('BOTTOMPADDING', (0,0), (-1,0), 6),
            ('TOPPADDING', (0,0), (-1,0), 6),
        ])
    if stripe:
        start_row = 1 if header else 0
        for i in range(start_row, len(data)):
            if (i - start_row) % 2 == 1:
                style_cmds.append(('BACKGROUND', (0,i), (-1,i), TABLE_STRIPE))
    t.setStyle(TableStyle(style_cmds))
    return t

# Content width helper (A4 - 40mm margins)
CONTENT_WIDTH = A4[0] - 40*mm


# ═══════════════════════════════════════════════════════════════════
# CONTENT BUILDERS
# ═══════════════════════════════════════════════════════════════════

def build_title_page():
    story = []
    story.append(Spacer(1, 30*mm))
    story.append(P('PRACTICEPRO', 'MetaLine'))
    story.append(Spacer(1, 4*mm))
    story.append(Paragraph('Codebase Audit &amp; Refactor Roadmap', STYLES['Title']))
    story.append(Paragraph('Applying the Van Cleif Methodology across the full stack', STYLES['Subtitle']))
    story.append(Spacer(1, 6*mm))
    story.append(HRFlowable(width='100%', thickness=0.6, color=ACCENT, spaceAfter=4*mm))
    story.append(P('A comprehensive review of security, structure, and polish across the Convex backend, React frontend, and shared infrastructure — with a prioritized, safe-by-default action plan.', 'Body'))
    story.append(Spacer(1, 6*mm))

    # Quick stats table
    stats_data = [
        [cell('Metric', 'TableHeader'), cell('Value', 'TableHeader'), cell('Status', 'TableHeader')],
        [cell('Total Convex functions'), cell('423 across 48 modules'), cell(severity_badge('MEDIUM'))],
        [cell('Total React components'), cell('339'), cell(severity_badge('MEDIUM'))],
        [cell('Schema tables'), cell('65'), cell(severity_badge('MEDIUM'))],
        [cell('TypeScript errors (baseline)'), cell('327'), cell(severity_badge('HIGH'))],
        [cell('TypeScript errors (post-fix)'), cell('315'), cell(severity_badge('SAFE'))],
        [cell('Build status'), cell('Passing (22s)'), cell(severity_badge('SAFE'))],
        [cell('Van Cleif pattern coverage'), cell('~35% of modules'), cell(severity_badge('HIGH'))],
        [cell('Critical security findings'), cell('6 (3 client-side, 3 server-side)'), cell(severity_badge('CRITICAL'))],
        [cell('Safe fixes applied this session'), cell('5 (12 TS errors cleared)'), cell(severity_badge('SAFE'))],
    ]
    t = styled_table(stats_data, [55*mm, 75*mm, 40*mm])
    story.append(t)
    story.append(Spacer(1, 12*mm))
    story.append(P('<b>Report date:</b> 16 August 2026 &nbsp;&nbsp;|&nbsp;&nbsp; <b>Audited commit:</b> HEAD of <code>origin/main</code> &nbsp;&nbsp;|&nbsp;&nbsp; <b>Auditor:</b> Super Z (independent)', 'MetaLine'))
    story.append(PageBreak())
    return story


def build_toc():
    story = []
    story.append(P('Contents', 'H1'))
    story.append(Spacer(1, 4*mm))
    toc = TableOfContents()
    toc.levelStyles = [STYLES['TocL0'], STYLES['TocL1']]
    story.append(toc)
    story.append(PageBreak())
    return story


def build_executive_summary():
    story = []
    story.append(add_heading('1. Executive Summary', STYLES['H1'], 0))

    story.append(P(
        'PracticePro is a mature, multi-product SaaS platform (Vega for legal practice, Atrium for property management, '
        'Komplete as the unified tier) built on React 18 + Vite 5 + Convex + Capacitor. The codebase has reached a stage '
        'where the polish patterns that were carefully applied to a small number of flagship modules — the '
        '<i>Van Cleif methodology</i> — have not been systematically extended to the rest of the system. This audit '
        'identifies the gaps, ranks them by impact and safety, and applies a first wave of surgical fixes that are '
        'demonstrably safe and worthwhile.'
    ))

    story.append(add_heading('1.1 What the Van Cleif Methodology Is', STYLES['H2'], 1))
    story.append(P(
        'Named for Van Cleef &amp; Arpels — the French haute joaillerie house famous for the "Sert Mystrieux" invisible '
        'setting, where the metalwork is hidden so the gems appear as a continuous surface — the Van Cleif methodology '
        'is a set of polish patterns that make a codebase behave predictably under stress. The "invisible setting" '
        'metaphor captures the goal: the user never sees the metalwork (the implementation), only the gems (the '
        'feature). Practically, the methodology is expressed through seven concrete patterns that are already visible '
        'in flagship modules such as <code>convex/feedback.ts</code>, <code>convex/retainerBilling.ts</code>, '
        '<code>src/constants/identityGuardrails.ts</code>, and the role-based Terms Acceptance flow.'
    ))

    # Pattern table
    pattern_data = [
        [cell('#', 'TableHeader'), cell('Pattern', 'TableHeader'), cell('What it guarantees', 'TableHeader'), cell('Reference implementation', 'TableHeader')],
        [cell('1'), cell('<b>Defense-in-depth gating</b>'), cell('Premium feature checks on BOTH client AND server, so a tampered client cannot bypass.'), cell('<code>isFirmPremiumRetainerEligible()</code> in retainerBilling.ts:108')],
        [cell('2'), cell('<b>Idempotency keys</b>'), cell('Retried writes return the original result instead of creating duplicates.'), cell('<code>idempotencyKey</code> + <code>by_idempotency</code> index in feedback.ts:30')],
        [cell('3'), cell('<b>Soft-delete with audit trail</b>'), cell('Destructive operations become reversible; deletedAt / deletedBy preserved.'), cell('<code>deleteFeedbackThread</code> in feedback.ts')],
        [cell('4'), cell('<b>Identity lock guardrails</b>'), cell('AI system prompt + post-processing validator prevent product-identity leakage.'), cell('<code>ABSOLUTE IDENTITY LOCK</code> in identityGuardrails.ts')],
        [cell('5'), cell('<b>Role-based access control</b>'), cell('Every mutation verifies caller role via <code>requireFirmUser</code> / <code>requireFounder</code> / <code>requireAdmin</code>.'), cell('<code>requireFirmUser</code> in authHelpers.ts')],
        [cell('6'), cell('<b>Per-product branching</b>'), cell('UI text and AI behaviour branch on <code>isProperty</code> for Atrium vs Vega.'), cell('<code>useProduct()</code> hook + <code>validateAIResponse(text, isProperty)</code>')],
        [cell('7'), cell('<b>Defensive auth fallback</b>'), cell('Legacy callers without userEmail get an anonymous context (not a hard throw) — fail-soft for backward compatibility.'), cell('<code>requireFirmUser</code> at authHelpers.ts:40-56')],
    ]
    story.append(styled_table(pattern_data, [8*mm, 38*mm, 70*mm, 54*mm]))
    story.append(P('<i>Table 1.1 — The seven Van Cleif patterns and their canonical implementations.</i>', 'Caption'))

    story.append(add_heading('1.2 Headline Findings', STYLES['H2'], 1))
    story.append(P(
        'The audit found three categories of work. <b>First</b>, the Convex backend contains two "God files" '
        '(<code>myFunctions.ts</code> at 6,279 lines and <code>portals.ts</code> at 5,970 lines) that together account '
        'for 151 of the codebase\'s exports; these files are too large to safely review, modify, or merge against, and '
        'they should be split into 30 domain-scoped modules. <b>Second</b>, several Convex modules bypass the Van Cleif '
        'auth pattern entirely — most alarmingly, <code>portals.ts</code> has 70+ exports but only ONE calls '
        '<code>requireFirmUser</code>, meaning a malicious caller who knows any firmId can post maintenance tickets, '
        'send portal messages, modify portal settings, and submit fake payment proofs against any firm. <b>Third</b>, '
        'the frontend has accumulated dead code (49 unused shadcn scaffolding files in <code>src/components/ui/</code> '
        'that contribute ~170 of the 327 baseline TypeScript errors) and several untrusted '
        '<code>dangerouslySetInnerHTML</code> sites that are not wrapped in <code>sanitize()</code>.'
    ))

    story.append(Paragraph(
        f'<b>Critical takeaway.</b> {severity_badge("CRITICAL")} The portals.ts multi-tenant isolation hole is the '
        'single highest-priority item in this audit. It is also the safest to fix: adding '
        '<code>requireFirmUser</code> calls is additive (only fails closed for missing userEmail, which the legacy '
        'fallback already handles) and requires no schema migration. This should be the very next change shipped.',
        STYLES['CalloutCritical']
    ))
    return story


def build_methodology_audit():
    story = []
    story.append(add_heading('2. Van Cleif Pattern Coverage Today', STYLES['H1'], 0))
    story.append(P(
        'Before recommending changes, this section maps the existing pattern coverage so the gaps are visible at a '
        'glance. The pattern coverage matrix below covers every Convex module with more than 100 lines of code. A '
        'green check means the pattern is consistently applied; a warning triangle means partial coverage (e.g. '
        'soft-delete exists for one table but not its siblings); a red cross means the pattern is entirely absent.'
    ))

    story.append(add_heading('2.1 Backend Pattern Gap Matrix', STYLES['H2'], 1))
    matrix_data = [
        [cell('Module (LOC)', 'TableHeader'),
         cell('Idempotency', 'TableHeader'),
         cell('Soft-delete', 'TableHeader'),
         cell('Defense-in-depth', 'TableHeader'),
         cell('RBAC', 'TableHeader'),
         cell('Verdict', 'TableHeader')],
        [cell('feedback.ts (671) — gold standard'), cell('YES'), cell('YES'), cell('n/a'), cell('partial'), cell(severity_badge('SAFE'))],
        [cell('retainerBilling.ts (847)'), cell('no'), cell('state-machine'), cell('YES'), cell('YES'), cell(severity_badge('SAFE'))],
        [cell('myFunctions.ts (6,279)'), cell('partial'), cell('no'), cell('partial'), cell('YES (48 calls)'), cell(severity_badge('HIGH'))],
        [cell('portals.ts (5,970)'), cell('no'), cell('partial'), cell('no'), cell('<b>1 of 70</b>'), cell(severity_badge('CRITICAL'))],
        [cell('founderMetrics.ts (2,394)'), cell('no'), cell('no'), cell('n/a'), cell('YES (30 calls)'), cell(severity_badge('MEDIUM'))],
        [cell('broadcasts.ts (565)'), cell('no'), cell('partial'), cell('no'), cell('<b>zero</b>'), cell(severity_badge('CRITICAL'))],
        [cell('backups.ts (471)'), cell('no'), cell('no'), cell('no'), cell('<b>zero — triggerBackupNow is public</b>'), cell(severity_badge('CRITICAL'))],
        [cell('sentry.ts (1,049) — financial mutations'), cell('no'), cell('no'), cell('no'), cell('<b>zero (23 exports)</b>'), cell(severity_badge('CRITICAL'))],
        [cell('legalRepo.ts (283)'), cell('no'), cell('no'), cell('no'), cell('zero'), cell(severity_badge('HIGH'))],
        [cell('trustAccount.ts (324)'), cell('no'), cell('no'), cell('partial'), cell('YES (4 calls)'), cell(severity_badge('HIGH'))],
        [cell('pushNotifications.ts (434)'), cell('no'), cell('no'), cell('no'), cell('zero (claims founder-only in comment)'), cell(severity_badge('HIGH'))],
        [cell('indexer.ts (197)'), cell('no'), cell('no'), cell('no'), cell('zero'), cell(severity_badge('HIGH'))],
        [cell('embeddings.ts (105)'), cell('no'), cell('no'), cell('no'), cell('zero — clearFirmMemories is public'), cell(severity_badge('CRITICAL'))],
        [cell('ai.ts (93)'), cell('no'), cell('n/a'), cell('no'), cell('zero'), cell(severity_badge('HIGH'))],
        [cell('visitorManagement.ts (604)'), cell('no'), cell('partial (revokedAt)'), cell('YES (VMS billing)'), cell('partial'), cell(severity_badge('MEDIUM'))],
        [cell('proactive.ts (918)'), cell('no'), cell('partial (dismissedAt)'), cell('n/a'), cell('n/a (internal)'), cell(severity_badge('SAFE'))],
        [cell('conversationMemory.ts (334)'), cell('no'), cell('n/a'), cell('n/a'), cell('n/a (internal)'), cell(severity_badge('SAFE'))],
        [cell('analytics.ts (277)'), cell('no'), cell('n/a'), cell('n/a'), cell('zero (trackEvent public)'), cell(severity_badge('MEDIUM'))],
    ]
    story.append(styled_table(matrix_data, [60*mm, 18*mm, 18*mm, 22*mm, 26*mm, 26*mm]))
    story.append(P('<i>Table 2.1 — Backend pattern coverage. "zero" means the auth helper is never invoked; this is the '
                   'most dangerous column because unauthenticated mutations are public endpoints on the Convex '
                   'deployment.</i>', 'Caption'))

    story.append(add_heading('2.2 Frontend Pattern Gap Matrix', STYLES['H2'], 1))
    story.append(P(
        'The frontend tells a parallel story. Of approximately 176 mutation call sites in <code>src/</code>, only 8 '
        'carry an <code>idempotencyKey</code> (concentrated in MessagesView and FeedbackForm). The remaining 168 sites '
        'are at double-submit risk — particularly on mobile networks where Capacitor retries are common. The table '
        'below highlights the highest-leverage gaps.'
    ))

    fe_matrix = [
        [cell('Component (mutation calls)', 'TableHeader'),
         cell('Idempotency', 'TableHeader'),
         cell('isProperty branch', 'TableHeader'),
         cell('useFeatures gate', 'TableHeader'),
         cell('Submit guard', 'TableHeader'),
         cell('Priority', 'TableHeader')],
        [cell('AloaChat.tsx (3 calls — saveMessage, createConv, deleteConv)'), cell('no'), cell('YES'), cell('no'), cell('partial'), cell(severity_badge('CRITICAL'))],
        [cell('DraftProEditor.tsx (AI drafting, save-as-template)'), cell('no'), cell('YES'), cell('no'), cell('partial'), cell(severity_badge('HIGH'))],
        [cell('TenantPortal.tsx (4 calls)'), cell('no'), cell('implicit'), cell('YES'), cell('YES'), cell(severity_badge('HIGH'))],
        [cell('MessagesView.tsx (4 calls — admin reply paths missing)'), cell('partial'), cell('YES'), cell('no'), cell('partial'), cell(severity_badge('HIGH'))],
        [cell('TermsAcceptance.tsx (recordTermsAcceptance)'), cell('no'), cell('role-based'), cell('n/a'), cell('<b>FIXED this session</b>'), cell(severity_badge('SAFE'))],
        [cell('VisitorPortal.tsx (generateVisitorToken, revoke)'), cell('no'), cell('n/a'), cell('no'), cell('no'), cell(severity_badge('HIGH'))],
        [cell('PaymentGatewayModal.tsx (createSubscriptionRequest)'), cell('no'), cell('n/a'), cell('no'), cell('partial'), cell(severity_badge('CRITICAL'))],
        [cell('ModalManager.tsx (recordConsent, addLedgerEntry)'), cell('no'), cell('n/a'), cell('no'), cell('partial'), cell(severity_badge('HIGH'))],
        [cell('BillingMonitorView.tsx (5 financial writes)'), cell('no'), cell('n/a'), cell('partial'), cell('partial'), cell(severity_badge('CRITICAL'))],
        [cell('TrustAccountTab.tsx (recordTransaction, deleteTransaction)'), cell('no'), cell('n/a'), cell('no'), cell('partial'), cell(severity_badge('HIGH'))],
        [cell('DataProvider.tsx (4 central mutations)'), cell('no'), cell('n/a'), cell('n/a'), cell('n/a'), cell(severity_badge('CRITICAL'))],
        [cell('AuthContext.tsx (5 mutations incl. deleteAccount)'), cell('no'), cell('n/a'), cell('n/a'), cell('no inflight state'), cell(severity_badge('CRITICAL'))],
    ]
    story.append(styled_table(fe_matrix, [60*mm, 18*mm, 20*mm, 20*mm, 22*mm, 30*mm]))
    story.append(P('<i>Table 2.2 — Frontend pattern coverage for the 12 highest-leverage components. The DataProvider '
                   'row is significant because it is the central choke point: adding idempotency here propagates to '
                   'every consumer automatically.</i>', 'Caption'))

    return story


def build_backend_audit():
    story = []
    story.append(add_heading('3. Backend Audit — Convex', STYLES['H1'], 0))
    story.append(P(
        'The Convex backend has 48 TypeScript modules totalling approximately 27,000 lines. Two files account for '
        'over 12,000 of those lines: <code>myFunctions.ts</code> (6,279 LOC, 81 exports) and <code>portals.ts</code> '
        '(5,970 LOC, 70 exports). Both files mix unrelated domains — auth, billing, messaging, maintenance tickets, '
        'invites, broadcasts, analytics — into single mega-files that are too large to safely review. This section '
        'proposes a domain-driven split that respects the existing module boundaries and minimizes import churn.'
    ))

    story.append(add_heading('3.1 The myFunctions.ts God File', STYLES['H2'], 1))
    story.append(P(
        'A line-count breakdown reveals 18 distinct domains crammed into one file. The largest cluster is Auth '
        '(26 exports, ~1,300 LOC) followed by Generic CRUD (7 exports), Subscriptions (9 exports), and Email Service '
        '(7 exports). The proposed split moves each cluster into a dedicated module under <code>convex/</code>, '
        'leaving <code>myFunctions.ts</code> as a thin re-export shim for backward compatibility during the migration. '
        'The split targets below are sized so that no new module exceeds ~700 lines.'
    ))

    split_data = [
        [cell('Domain cluster', 'TableHeader'), cell('Exports', 'TableHeader'), cell('Representative exports', 'TableHeader'), cell('Proposed module', 'TableHeader')],
        [cell('Auth & users'), cell('26'), cell('verifyLogin, startSignup, createUser, deactivateTeamMember, validateInviteCode, joinFirm'), cell('convex/auth.ts')],
        [cell('Firm CRUD'), cell('8'), cell('getFirmData, createFirm, updateFirmSettings, deleteFirm, getJoinedFirms'), cell('convex/firms.ts')],
        [cell('Generic CRUD'), cell('7'), cell('createItem, updateItem, deleteItem, forceDeleteItem, purgeFirmData'), cell('convex/genericCrud.ts')],
        [cell('Chat / messaging'), cell('8'), cell('sendChatMessage (has idempotency), saveAloaMessage, getAloaConversations'), cell('convex/chat.ts')],
        [cell('Email service (Brevo)'), cell('7'), cell('sendVerificationEmail, sendRecoveryEmail, sendBreachNotification'), cell('convex/emailService.ts')],
        [cell('Subscriptions'), cell('9'), cell('createSubscriptionRequest, approveSubscriptionRequest, expireTrials'), cell('convex/subscriptions.ts')],
        [cell('Add-ons / VMS billing'), cell('9'), cell('startVmsAddonTrial, activateVmsAddon, cancelVmsAddon'), cell('convex/addons.ts')],
        [cell('Admin user ops'), cell('3'), cell('adminSearchUsersByEmail, adminDeleteUser, adminForceVerify'), cell('convex/adminUsers.ts')],
        [cell('Cascade deletes'), cell('3'), cell('deleteMatterCascade, deletePropertyCascade, deleteContactCascade'), cell('convex/cascadeDeletes.ts')],
        [cell('Broadcast engine'), cell('4'), cell('getAllUsersForBroadcast, createBroadcastNotification'), cell('merge into convex/broadcasts.ts')],
        [cell('Presence'), cell('4'), cell('sendHeartbeat, getActivePeers, diagnoseConnectivity'), cell('convex/presence.ts')],
        [cell('Tasks'), cell('3'), cell('createTask, updateTask, updateTaskStatus'), cell('convex/tasks.ts')],
        [cell('Matters / properties reads'), cell('3'), cell('getMatterDetails, getPropertyDetails, getPropertyById'), cell('convex/matters.ts + convex/properties.ts')],
        [cell('Other (terms, notifications, WhatsApp quota, etc.)'), cell('12'), cell('recordTermsAcceptance, markNotificationsAsRead, incrementWhatsAppQuota'), cell('5 small modules')],
    ]
    story.append(styled_table(split_data, [38*mm, 14*mm, 70*mm, 48*mm]))
    story.append(P('<i>Table 3.1 — Domain-cluster split for myFunctions.ts. 81 exports total; largest cluster (Auth) '
                   'is 32% of the file. Migration can be done cluster-by-cluster behind a re-export shim.</i>', 'Caption'))

    story.append(add_heading('3.2 The portals.ts Multi-Tenant Hole', STYLES['H2'], 1))
    story.append(Paragraph(
        f'<b>Severity: {severity_badge("CRITICAL")} &nbsp; Effort to fix: low &nbsp; Risk to fix: very low</b><br/><br/>'
        'A grep for <code>requireFirmUser|requireFounder|requireAdmin</code> in portals.ts returns only two matches: '
        'the import statement at line 4 and one call at line 307 inside <code>completePortalTask</code>. The remaining '
        '69 exports accept a client-supplied <code>firmId</code> argument and write directly to the database. A '
        'malicious caller who knows any firmId (which is exposed in portal invite URLs, in user JWTs, and in many '
        'public query responses) can: post maintenance tickets against any firm '
        '(<code>createMaintenanceTicket</code> L19); send portal messages impersonating any user '
        '(<code>sendPortalMessage</code> L3941); modify portal settings for any firm '
        '(<code>updateFirmPortalSettings</code> L5003); and submit fake payment proofs '
        '(<code>submitPaymentProof</code> L4644). The fix is purely additive: prepend each mutation with '
        '<code>const ctx = await requireFirmUser(args.userEmail, args.firmId);</code> — the existing defensive '
        'fallback in authHelpers.ts:40-56 already handles legacy callers that do not pass userEmail.',
        STYLES['CalloutCritical']
    ))

    story.append(add_heading('3.3 Cross-Module Duplication', STYLES['H2'], 1))
    story.append(P(
        'Several utility functions are duplicated across modules with divergent behaviour. The most dangerous case '
        'is <code>computeNextBillingDate</code>, which exists in three copies: the canonical implementation in '
        'retainerBilling.ts:62 (correctly clamps to month-end), and two private re-implementations in '
        'myFunctions.ts:5656 and founderMetrics.ts:1784 that silently produce wrong results for end-of-month dates. '
        'A consolidation pass should extract these into a <code>convex/dateUtils.ts</code> module and a '
        '<code>convex/moneyUtils.ts</code> module (the latter already exists with <code>roundMoney()</code> but is '
        'only used in two places — the other 14 inline <code>Math.round(num * 100) / 100</code> sites should be '
        'replaced with calls to it).'
    ))

    dup_data = [
        [cell('Duplicated helper', 'TableHeader'), cell('Copies', 'TableHeader'), cell('Files (line)', 'TableHeader'), cell('Consolidation target', 'TableHeader')],
        [cell('computeNextBillingDate (calendar math)'), cell('3 (divergent!)'), cell('retainerBilling.ts:62, myFunctions.ts:5656, founderMetrics.ts:1784'), cell('convex/dateUtils.ts')],
        [cell('Math.round(num*100)/100 (money rounding)'), cell('3'), cell('moneyUtils.ts:19, myFunctions.ts:3397, founderMetrics.ts:2319'), cell('use moneyUtils.roundMoney')],
        [cell('new Date().toISOString().split("T")[0]'), cell('14 occurrences'), cell('analytics, founderMetrics, visitorManagement, crons, proactive, backups'), cell('dateUtils.isoDate()')],
        [cell('generatePortalAccessToken (UUID v4)'), cell('1 file, 5 calls'), cell('portals.ts:11'), cell('extend convex/portalSecurity.ts')],
        [cell('BREVO_SENDER + HTML email wrapper'), cell('3 sets'), cell('myFunctions.ts:3707, portals.ts:5631, portals.ts:5911'), cell('convex/emailService.ts')],
        [cell('logSecurityEventInline (try/catch security sink)'), cell('3 sites'), cell('securityHelpers.ts:98, authHelpers.ts:60/101/120'), cell('export from securityHelpers')],
        [cell('Inline notification-insert block (8 lines)'), cell('13+ sites'), cell('myFunctions.ts (8), portals.ts (5+), feedback.ts (1)'), cell('notifyUser() helper')],
    ]
    story.append(styled_table(dup_data, [50*mm, 20*mm, 60*mm, 40*mm]))
    story.append(P('<i>Table 3.2 — Cross-module duplication catalog. The "divergent!" annotation on '
                   'computeNextBillingDate is the most concerning: the three copies produce different results for '
                   'the same input, which means billing dates are silently wrong for any code path that uses the '
                   'non-canonical copies.</i>', 'Caption'))

    story.append(add_heading('3.4 Schema Gaps', STYLES['H2'], 1))
    story.append(P(
        'The <code>archive</code> table (schema.ts:672) was created as the soft-delete infrastructure — it is '
        'designed to snapshot a row before destructive deletion. Today, no mutation populates it. Meanwhile, 18 '
        'tables are hard-deleted via <code>db.delete()</code> calls scattered across myFunctions.ts (18 sites), '
        'portals.ts (5 sites), and individual modules (sentry.ts, indexer.ts, embeddings.ts, securityHelpers.ts). '
        'The most impactful tables to convert are: <code>matters</code>, <code>contacts</code>, <code>properties</code> '
        '(all deleted via cascade functions that destroy legal/financial records); <code>invoices</code> '
        '(NDPA financial-audit requirement); <code>trust_transactions</code> (hard-deleted by '
        '<code>deleteTrustTransaction</code> in trustAccount.ts:303 — destroys the financial audit trail); '
        '<code>users</code> (should set <code>deactivatedAt</code>, which already exists, instead of hard delete); '
        'and <code>chatMessages</code> (has <code>isDeleted</code> flag but no <code>deletedAt</code>/<code>deletedBy</code> '
        'audit fields). Conversion is additive: add <code>deletedAt</code>, <code>deletedBy</code>, and '
        '<code>deletedReason</code> fields with a <code>by_firm_deleted</code> index, then change '
        '<code>db.delete()</code> calls to patch operations.'
    ))
    return story


def build_frontend_audit():
    story = []
    story.append(add_heading('4. Frontend Audit — React + Vite', STYLES['H1'], 0))
    story.append(P(
        'The frontend consists of 339 React components totalling roughly 151,000 lines of TypeScript/TSX. Nine '
        'components exceed 1,500 lines and account for ~25,000 lines on their own. The largest is '
        '<code>TenantPortal.tsx</code> at 3,879 lines, which packs 10 distinct tab views, 13 inline SVG icon '
        'components, Paystack checkout setup, document printing, and feedback submission into a single function '
        'component. This is the canonical "god component" anti-pattern: it cannot be safely reviewed, it re-renders '
        'on every keystroke (zero <code>useMemo</code>, zero <code>useCallback</code>), and any change risks '
        'breaking unrelated tabs.'
    ))

    story.append(add_heading('4.1 God Components — Extraction Plan', STYLES['H2'], 1))
    god_data = [
        [cell('File (LOC)', 'TableHeader'), cell('Inline sub-components to extract', 'TableHeader'), cell('Target directory', 'TableHeader'), cell('Root LOC after', 'TableHeader')],
        [cell('TenantPortal.tsx (3,879)'), cell('DashboardTab, NoticesTab, LedgerTab, ReceiptsTab, MaintenanceTab, MessagesTab, PaymentsTab, DocumentsTab, HelpAndSupportTab + 13 inline SVG icons'), cell('src/components/tenant/tabs/*.tsx'), cell('~250')],
        [cell('DraftProEditor.tsx (3,798)'), cell('28 inline SVG icons (1,100 LOC), FONTS/SIZES constants, ToolbarGroup/ToolbarBtn, AutoPagination plugin, CitationCard, FillPlaceholdersModal, RedraftModal, SaveAsTemplateModal, useDraftStream hook'), cell('src/components/documents/tiptap/* + hooks/*'), cell('~600')],
        [cell('AloaChat.tsx (3,455)'), cell('useLiveAudio hook, useChatScrollAnchor hook, ToolDispatcher, MessageList, Composer, InsightsPanel + ZERO useMemo today'), cell('src/components/aloa/* + hooks/*'), cell('~400')],
        [cell('MessagesView.tsx (3,315)'), cell('ChatWindow, MessageContent, InlineTicketReply, SectionHeader, 4 inbox sub-sections'), cell('src/components/messaging/*'), cell('~500')],
        [cell('PropertyDetailView.tsx (2,834)'), cell('UnitSwitcher, PropertyTicketsTab, PropertyNoticesTab, LinkedMattersTab, lease calculators'), cell('src/components/details/property/*'), cell('~600')],
        [cell('ClientDashboard.tsx (2,020)'), cell('StageBadge, SummaryCard, TabButton, EmptyState, FileTypeIcon + 6 tab bodies'), cell('src/components/client/tabs/*'), cell('~400')],
        [cell('PropertyForm.tsx (2,012)'), cell('useUnitRentalCalc hook, AccordionSection (reusable), 7 section sub-forms'), cell('src/components/forms/property/sections/*'), cell('~500')],
        [cell('LandingPage.tsx (1,581)'), cell('NavBar, Footer, HubHero, HomeSection, FeaturesSection, PricingSection, SceCalculatorModal + 3 button primitives'), cell('src/components/marketing/*'), cell('~100')],
        [cell('App.tsx (1,531)'), cell('ViewWrapper, MainContent, AppRouter, useAuthedRoutes / usePortalRouteParser / useIdleAutoLogout hooks + lazyWithReload util'), cell('src/components/layout/* + utils/*'), cell('~400')],
    ]
    story.append(styled_table(god_data, [40*mm, 80*mm, 35*mm, 20*mm]))
    story.append(P('<i>Table 4.1 — Extraction plan for the 9 god components. The "Root LOC after" column assumes all '
                   'inline sub-components are extracted; total reduction is ~22,000 lines moved out of monolithic '
                   'files into focused, testable modules.</i>', 'Caption'))

    story.append(add_heading('4.2 Security Findings — Stored XSS', STYLES['H2'], 1))
    story.append(P(
        'Ten files use <code>dangerouslySetInnerHTML</code>. Six of them route through <code>parseAloaMarkdown</code> '
        'which calls <code>sanitize()</code> (the safe path). Four of them inject untrusted HTML directly without '
        'sanitization, creating stored-XSS or prompt-injection attack vectors. The fix is mechanical: wrap each '
        'untrusted input in <code>sanitize()</code> from <code>src/utils/sanitization.ts</code> (which uses DOMPurify '
        'with a strict allowlist and is already used by AloaChat, NoteDetails, and ResourcesPage).'
    ))

    xss_data = [
        [cell('File:Line', 'TableHeader'), cell('Source of HTML', 'TableHeader'), cell('Risk', 'TableHeader'), cell('Status', 'TableHeader')],
        [cell('DocumentDetailView.tsx:252'), cell('Server-stored document content'), cell('Stored XSS — user A saves doc with &lt;script&gt;, user B views it'), cell(severity_badge('SAFE') + ' FIXED')],
        [cell('HtmlPagePreview.tsx:173'), cell('DraftPro editor output'), cell('Same as above (DraftPro content)'), cell(severity_badge('SAFE') + ' FIXED')],
        [cell('HtmlPagePreview.tsx:815'), cell('Paginated version of DraftPro output'), cell('Same as above'), cell(severity_badge('SAFE') + ' FIXED')],
        [cell('ResearchStudio.tsx:145'), cell('AI research output'), cell('Prompt-injection XSS — LLM can be tricked into emitting &lt;img onerror&gt;'), cell(severity_badge('SAFE') + ' FIXED')],
        [cell('ui/chart.tsx:83'), cell('Recharts internal CSS'), cell('Low (trusted library)'), cell(severity_badge('LOW') + ' no action')],
        [cell('AloaChat.tsx:2877'), cell('AI markdown via parseAloaMarkdown'), cell('Safe (routes through sanitize)'), cell(severity_badge('SAFE'))],
    ]
    story.append(styled_table(xss_data, [40*mm, 40*mm, 65*mm, 30*mm]))
    story.append(P('<i>Table 4.2 — Untrusted HTML injection sites. All four critical sites were fixed in this audit '
                   'session by wrapping the HTML in <code>sanitize()</code> before injection.</i>', 'Caption'))

    story.append(add_heading('4.3 Auth &amp; Session UX — Critical Risks', STYLES['H2'], 1))
    story.append(P(
        'The authentication layer has three architectural risks that pre-date this audit and require a coordinated '
        'fix. They are flagged here as recommendations rather than applied because the fix touches every portal '
        'route, every Convex caller, and four localStorage keys — too large a blast radius for an audit-session patch. '
        'A dedicated security sprint should be scheduled to address them.'
    ))

    auth_data = [
        [cell('Risk', 'TableHeader'), cell('Detail', 'TableHeader'), cell('Fix scope', 'TableHeader')],
        [cell(f'{severity_badge("CRITICAL")} Email-as-token'),
         cell('AuthContext.getInitialToken() returns the user\'s lowercased email as the session token. No JWT, no opaque token, no expiry. Stored in 4 localStorage/sessionStorage slots in plaintext. Anyone who exfiltrates an email can impersonate.'),
         cell('Issue opaque server-side session token; rotate on each login; expire after 30d.')],
        [cell(f'{severity_badge("CRITICAL")} Unsigned ?impersonate= param'),
         cell('Appending ?impersonate=admin@firm.com to any URL writes that email to localStorage and returns it as the token. No signature, no nonce, no founder-secret. Universally accessible.'),
         cell('Require a signed, short-lived impersonateToken issued by a founder-only mutation.')],
        [cell(f'{severity_badge("HIGH")} Plaintext PII in localStorage'),
         cell('practicepro_cached_user stores email, firmId, barNumber, accessibleMatterIds, portalAccessToken in plaintext. Violates NDPA 25 (data minimization). Any XSS payload can read it.'),
         cell('Encrypt with WebCrypto + a per-session key derived from a server-issued nonce.')],
        [cell(f'{severity_badge("HIGH")} Gemini API key in plaintext'),
         cell('practicepro_custom_gemini_key is synced from server to localStorage without encryption. Any XSS can exfiltrate it (and bill the firm).'),
         cell('Keep key server-side only; proxy all Gemini calls through a Convex action.')],
        [cell(f'{severity_badge("MEDIUM")} useFeatures permissive default'),
         cell('When firmDetails.subscriptionPlan is undefined (still loading), portal users default to Komplete (full access). A portal user whose firm data fails to load sees ALL premium features unlocked until the firm data arrives.'),
         cell('Default to Core (deny-by-default); unlock on firm-data arrival.')],
    ]
    story.append(styled_table(auth_data, [40*mm, 75*mm, 55*mm]))
    story.append(P('<i>Table 4.3 — Auth &amp; session UX risks ranked by severity. The top two rows are '
                   'pre-existing critical risks that require a dedicated security sprint; they are too large a blast '
                   'radius for an audit-session patch.</i>', 'Caption'))

    story.append(add_heading('4.4 Performance Red Flags', STYLES['H2'], 1))
    story.append(P(
        'Two performance issues stand out. <b>First</b>, <code>AloaChat.tsx</code> — 3,455 lines — has zero '
        '<code>useMemo</code> and only two <code>useCallback</code> declarations. Every keystroke in the composer '
        're-renders the entire chat history, recreates the Web Audio graph, and rebuilds the citation registry. '
        'This is the single highest-impact memoization fix in the codebase. <b>Second</b>, only 5 of approximately 25 '
        'top-level views are lazy-loaded (App.tsx:43-62 — the <code>lazyWithReload</code> wrapper is excellent). The '
        'other 20 views — including the 3,879-line TenantPortal, the 2,020-line ClientDashboard, and the 1,581-line '
        'LandingPage — are statically imported, shipping ~12,000 lines of code in the main chunk that is never '
        'executed for users who do not visit those routes.'
    ))

    perf_data = [
        [cell('Issue', 'TableHeader'), cell('Impact', 'TableHeader'), cell('Fix', 'TableHeader')],
        [cell('AloaChat zero useMemo/useCallback'),
         cell('Every keystroke re-renders entire chat history (3,455 LOC). Audio graph + citation registry recreated per render.'),
         cell('Wrap messages, citationRegistryRef, parseAloaMarkdown output in useMemo. Risk: stale-closure bugs if deps wrong — needs careful testing.')],
        [cell('20 views statically imported'),
         cell('~12,000 LOC shipped in main chunk that is never executed for most users.'),
         cell('Wrap TenantPortal, ClientDashboard, PropertyDetailView, SettingsView, LandingPage in lazyWithReload + Suspense. Pattern already established.')],
        [cell('Duplicate notification queries'),
         cell('Header.tsx and NotificationCenter.tsx both fire getUserNotifications + getUnreadNotificationCount on every authenticated render.'),
         cell('Lift to a useNotifications() hook; single source of truth.')],
        [cell('BillingMonitorView over-fetching'),
         cell('Fires getOutboxForFirm + getOutboxStats for ALL firms including Atrium (which has no retainer billing).'),
         cell('Skip query when !isProperty or !canUseRetainerAutoBilling.')],
        [cell('useScrollParallax no rAF throttle'),
         cell('LandingPage scroll listener fires on every pixel; no requestAnimationFrame throttle.'),
         cell('Wrap in rAF; reuse FlashlightBackground pattern from ConvexErrorBoundary.tsx:78-92.')],
    ]
    story.append(styled_table(perf_data, [50*mm, 65*mm, 55*mm]))
    story.append(P('<i>Table 4.4 — Top 5 performance red flags. The AloaChat memoization is the highest-leverage fix '
                   'but also the riskiest — incorrect dependency arrays will cause stale-closure bugs in the streaming '
                   'audio and citation paths.</i>', 'Caption'))

    return story


def build_typescript_health():
    story = []
    story.append(add_heading('5. TypeScript Health', STYLES['H1'], 0))
    story.append(P(
        'The codebase has a baseline of 327 TypeScript errors. This audit applied five surgical fixes that reduced '
        'the count to 315 (12 errors cleared) without any behavioural change. The remaining errors are concentrated '
        'in three areas: 49 dead shadcn scaffolding files in <code>src/components/ui/</code> that reference packages '
        'not installed in this project (radix-ui, clsx, tailwind-merge, class-variance-authority); the gemini service '
        'model union that was missing the <code>"research"</code> literal; and a handful of nullability issues in '
        'utility files. None of the remaining errors are blockers — the production build passes cleanly via Vite — '
        'but clearing them would significantly improve developer experience and the reliability of IDE refactors.'
    ))

    story.append(add_heading('5.1 Errors Fixed in This Session', STYLES['H2'], 1))
    fixed_data = [
        [cell('Fix', 'TableHeader'), cell('File', 'TableHeader'), cell('Errors cleared', 'TableHeader'), cell('Risk', 'TableHeader')],
        [cell('Removed duplicate <code>useQuery</code> + <code>api</code> imports (wrong path was <code>../convex/_generated/api</code> instead of <code>../../convex/_generated/api</code>)'),
         cell('src/components/Header.tsx:5-6'), cell('5'), cell(severity_badge('SAFE'))],
        [cell('Added <code>"research"</code> literal to modelPreference union (already used in code at lines 321, 364, 608, 622)'),
         cell('src/services/geminiService.ts:286, 575'), cell('5 (cascade)'), cell(severity_badge('SAFE'))],
        [cell('Fixed <code>cachedIsNative</code> nullability — module-level let cannot be narrowed by TS after assignment'),
         cell('src/utils/capacitor.ts:30-32, 44-45'), cell('1'), cell(severity_badge('SAFE'))],
        [cell('Wrapped 4 untrusted <code>dangerouslySetInnerHTML</code> sites in <code>sanitize()</code>'),
         cell('DocumentDetailView:252, HtmlPagePreview:173/815, ResearchStudio:145'), cell('0 (security fix)'), cell(severity_badge('SAFE'))],
        [cell('Added <code>isSubmitting</code> guard to TermsAcceptance.handleAccept + disabled Accept button during await'),
         cell('src/components/TermsAcceptance.tsx:148-182, 237-243'), cell('0 (UX fix)'), cell(severity_badge('SAFE'))],
    ]
    story.append(styled_table(fixed_data, [60*mm, 40*mm, 25*mm, 25*mm]))
    story.append(P('<i>Table 5.1 — Five surgical fixes applied in this audit session. All are additive (no '
                   'behavioural change for legitimate callers) and verified by a clean Vite production build (22s). '
                   'The build was confirmed to pass before and after the changes.</i>', 'Caption'))

    story.append(add_heading('5.2 Top 5 Remaining Quick Wins', STYLES['H2'], 1))
    story.append(P(
        'The remaining 315 errors break down into clear categories. The single biggest win — accounting for '
        'approximately 170 of the 315 errors — is to delete the 49 dead shadcn scaffolding files in '
        '<code>src/components/ui/</code>. These files reference packages that are not installed in this project '
        '(verified: <code>radix-ui</code>, <code>clsx</code>, <code>tailwind-merge</code>, '
        '<code>class-variance-authority</code> are all absent from <code>package.json</code>). They were scaffolded '
        'by <code>shadcn-ui</code> at some point but never wired in. The only file in that directory that is actually '
        'imported by the rest of the codebase is <code>ConfirmDialog.tsx</code> (15 importers verified). The other '
        '49 files plus <code>CognitiveGuidance.tsx</code> (zero importers) can be deleted in a single commit.'
    ))

    wins_data = [
        [cell('#', 'TableHeader'), cell('Fix', 'TableHeader'), cell('Errors cleared', 'TableHeader'), cell('Effort', 'TableHeader'), cell('Risk', 'TableHeader')],
        [cell('1'), cell('Delete 49 dead shadcn files + CognitiveGuidance.tsx (zero importers verified)'),
         cell('~170 (55% of remaining)'), cell('1 hour'), cell(severity_badge('SAFE'))],
        [cell('2'), cell('Add <code>idempotencyKey</code> + <code>attachments</code> to sendChatMessage arg type (client passes both; server type only knows idempotencyKey)'),
         cell('8 (3 direct + 5 cascade)'), cell('15 min'), cell(severity_badge('SAFE'))],
        [cell('3'), cell('Add <code>enabled</code> field to PostHog config type in src/utils/analytics.ts:35'),
         cell('1'), cell('5 min'), cell(severity_badge('SAFE'))],
        [cell('4'), cell('Fix <code>LocalNotificationSchema.data</code> access in src/utils/notifications.ts:137'),
         cell('1'), cell('10 min'), cell(severity_badge('SAFE'))],
        [cell('5'), cell('Fix <code>string | null</code> to <code>string | undefined</code> in propertyPayload.ts:106-108'),
         cell('3'), cell('10 min'), cell(severity_badge('SAFE'))],
    ]
    story.append(styled_table(wins_data, [8*mm, 70*mm, 30*mm, 18*mm, 22*mm]))
    story.append(P('<i>Table 5.2 — Top 5 remaining quick wins. Together they would clear ~183 of the 315 remaining '
                   'errors (58%) in under 2 hours, all with very low risk.</i>', 'Caption'))

    return story


def build_roadmap():
    story = []
    story.append(add_heading('6. Refactor Roadmap — Prioritized &amp; Sequenced', STYLES['H1'], 0))
    story.append(P(
        'The recommendations are grouped into three phases, ordered by safety and dependency. Phase 1 is purely '
        'additive security work — no schema changes, no behavioural change for legitimate callers — and should '
        'ship first. Phase 2 adds data-integrity infrastructure (idempotency keys, soft-delete fields) that requires '
        'additive schema migrations but no data backfill. Phase 3 is pure code organization (module splits, god '
        'component extraction, dead code removal) and can be done incrementally behind re-export shims. Each phase '
        'is designed so that any individual item can be shipped independently of the others.'
    ))

    story.append(add_heading('6.1 Phase 1 — Security (1-2 days, additive only)', STYLES['H2'], 1))
    story.append(Paragraph(
        '<b>Goal:</b> Close the multi-tenant isolation hole in portals.ts and add auth gates to the other unauthenticated '
        'modules. <b>Constraint:</b> All changes are additive — they only fail closed for missing userEmail, which the '
        'legacy fallback already handles. No schema migration, no behavioural change for legitimate callers.',
        STYLES['Callout']
    ))

    p1_data = [
        [cell('#', 'TableHeader'), cell('Refactor', 'TableHeader'), cell('Impact', 'TableHeader'), cell('Safety', 'TableHeader'), cell('Effort', 'TableHeader')],
        [cell('P1.1'), cell('Add <code>requireFirmUser</code> to 40 unauthenticated portals.ts mutations'),
         cell(severity_badge('CRITICAL') + ' multi-tenant isolation'), cell('very high'), cell('4 hours')],
        [cell('P1.2'), cell('Add <code>requireFirmUser</code>/<code>requireFounder</code> to sentry.ts (23 financial mutations)'),
         cell(severity_badge('CRITICAL') + ' financial integrity'), cell('high'), cell('1 day')],
        [cell('P1.3'), cell('Add <code>requireFounder</code> to embeddings.clearFirmMemories, indexer.deleteAloaDocument/saveAloaDocument'),
         cell(severity_badge('CRITICAL') + ' firm-data destruction'), cell('very high'), cell('2 hours')],
        [cell('P1.4'), cell('Add <code>requireFounder</code> to pushNotifications.notifyAppUpdate/sendToUsers/sendTestPush/sendTestPushToUser'),
         cell(severity_badge('HIGH') + ' push spam vector'), cell('very high'), cell('2 hours')],
        [cell('P1.5'), cell('Add <code>requireFounder</code> to salesInquiries.listSalesInquiries/updateInquiryStatus'),
         cell(severity_badge('MEDIUM') + ' founder-data leak'), cell('very high'), cell('1 hour')],
        [cell('P1.6'), cell('Add <code>requireFounder</code> to backups.triggerBackupNow'),
         cell(severity_badge('CRITICAL') + ' unauthenticated backup trigger'), cell('very high'), cell('30 min')],
        [cell('P1.7'), cell('Add <code>requireFounder</code> to analytics.getDashboardData/getFirmsList'),
         cell(severity_badge('MEDIUM') + ' founder-data leak'), cell('very high'), cell('1 hour')],
    ]
    story.append(styled_table(p1_data, [12*mm, 80*mm, 40*mm, 22*mm, 18*mm]))
    story.append(P('<i>Table 6.1 — Phase 1 priorities. All additive, all close fail-closed for missing userEmail. '
                   'Estimated total: 1-2 days; should ship as a single PR.</i>', 'Caption'))

    story.append(add_heading('6.2 Phase 2 — Data Integrity (3-5 days, additive schema)', STYLES['H2'], 1))
    story.append(Paragraph(
        '<b>Goal:</b> Add idempotency keys to all retryable writes; convert hard-deletes to soft-deletes with audit '
        'trail. <b>Constraint:</b> Schema changes are additive (new optional fields + new indexes); existing rows '
        'default to null and behave as before. No data backfill required. Pattern is already proven in feedback.ts '
        'and sendChatMessage — this phase simply extends it to the rest of the codebase.',
        STYLES['Callout']
    ))

    p2_data = [
        [cell('#', 'TableHeader'), cell('Refactor', 'TableHeader'), cell('Impact', 'TableHeader'), cell('Safety', 'TableHeader'), cell('Effort', 'TableHeader')],
        [cell('P2.1'), cell('Add <code>idempotencyKey</code> + <code>by_idempotency</code> index to 5 critical tables (payment_proofs, subscriptionRequests, subscriptionAddons, termsAcceptance, tasks)'),
         cell(severity_badge('HIGH') + ' double-submit on financial/legal'), cell('high'), cell('1 day')],
        [cell('P2.2'), cell('Convert <code>deleteItem</code> + <code>forceDeleteItem</code> + 3 cascade deletes to soft-delete via <code>archive</code> table (already exists at schema.ts:672)'),
         cell(severity_badge('HIGH') + ' NDPA compliance + reversibility'), cell('medium (large blast radius — do table-by-table)'), cell('2 days')],
        [cell('P2.3'), cell('Convert <code>trustAccount.deleteTrustTransaction</code> to soft-delete'),
         cell(severity_badge('HIGH') + ' financial audit trail'), cell('high (single mutation)'), cell('2 hours')],
        [cell('P2.4'), cell('Add <code>deletedAt</code>/<code>deletedBy</code> to <code>chatMessages</code> (already has <code>isDeleted</code> flag) and to <code>aloaConversations</code>/<code>aloaMessages</code>'),
         cell(severity_badge('MEDIUM') + ' conversation audit trail'), cell('high'), cell('4 hours')],
        [cell('P2.5'), cell('Convert <code>adminDeleteUser</code> + <code>deleteAccount</code> to set <code>deactivatedAt</code> (already exists) instead of <code>db.delete()</code>'),
         cell(severity_badge('HIGH') + ' user audit trail + GDPR/NDPA right-to-be-forgotten'), cell('high'), cell('3 hours')],
    ]
    story.append(styled_table(p2_data, [12*mm, 80*mm, 40*mm, 22*mm, 18*mm]))
    story.append(P('<i>Table 6.2 — Phase 2 priorities. The archive table at schema.ts:672 is already provisioned but '
                   'unused today — this phase lights it up. P2.2 has the largest blast radius (touches ~18 deletion '
                   'sites across myFunctions.ts + portals.ts) and should be done table-by-table to limit '
                   'regression risk.</i>', 'Caption'))

    story.append(add_heading('6.3 Phase 3 — Code Organization (1-2 weeks, behind shims)', STYLES['H2'], 1))
    story.append(Paragraph(
        '<b>Goal:</b> Split the two God files; extract god components; remove dead code; consolidate duplicated '
        'helpers. <b>Constraint:</b> All changes are pure code reorganization — no behavioural change. Module '
        'splits should ship behind a re-export shim (myFunctions.ts becomes a thin file that re-exports from the '
        'new domain modules) so callers do not need to update imports in lockstep. God component extraction can be '
        'done one component at a time. Dead code removal is the lowest-risk item and can ship first to clear ~170 '
        'TypeScript errors as a quick morale win.',
        STYLES['Callout']
    ))

    p3_data = [
        [cell('#', 'TableHeader'), cell('Refactor', 'TableHeader'), cell('Impact', 'TableHeader'), cell('Safety', 'TableHeader'), cell('Effort', 'TableHeader')],
        [cell('P3.1'), cell('Delete 49 dead shadcn files + CognitiveGuidance.tsx (zero importers verified)'),
         cell(severity_badge('MEDIUM') + ' ~170 TS errors + bundle shrinks ~50KB'), cell('very high'), cell('1 hour')],
        [cell('P3.2'), cell('Lazy-load TenantPortal, ClientDashboard, PropertyDetailView, SettingsView, LandingPage via lazyWithReload'),
         cell(severity_badge('HIGH') + ' ~12,000 LOC out of main chunk'), cell('high'), cell('2 hours')],
        [cell('P3.3'), cell('Consolidate formatNaira + formatDate into src/utils/formatting.ts (13 inline copies)'),
         cell(severity_badge('MEDIUM') + ' consistency + bug-fix propagation'), cell('very high (pure mechanical)'), cell('1 hour')],
        [cell('P3.4'), cell('Extract DraftProEditor inline SVGs (28 icons, ~1,100 LOC) to lucide-react or toolkit/Icon'),
         cell(severity_badge('MEDIUM') + ' file drops 3,798 to ~2,700 LOC'), cell('high'), cell('2 hours')],
        [cell('P3.5'), cell('Split myFunctions.ts into 18 domain modules behind re-export shim'),
         cell(severity_badge('MEDIUM') + ' maintainability + build time'), cell('medium (80 import sites to update)'), cell('3 days')],
        [cell('P3.6'), cell('Split portals.ts into 12 portal/* modules behind re-export shim'),
         cell(severity_badge('MEDIUM') + ' maintainability'), cell('medium (50+ import sites)'), cell('2 days')],
        [cell('P3.7'), cell('Extract TenantPortal 10 tab sub-components'),
         cell(severity_badge('MEDIUM') + ' file drops 3,879 to ~250 LOC'), cell('medium (firm-scoped queries need careful prop passing)'), cell('1 day')],
        [cell('P3.8'), cell('Add useMemo to AloaChat message list + citation registry (ZERO useMemo today)'),
         cell(severity_badge('HIGH') + ' single biggest perf win'), cell('medium (stale-closure risk in streaming paths)'), cell('2 hours + testing')],
        [cell('P3.9'), cell('Consolidate computeNextBillingDate (3 divergent copies) into convex/dateUtils.ts'),
         cell(severity_badge('HIGH') + ' silent billing-date bugs today'), cell('very high (pure functions)'), cell('2 hours')],
        [cell('P3.10'), cell('Hoist useNotifications hook (eliminates duplicate notification queries)'),
         cell(severity_badge('MEDIUM') + ' network efficiency'), cell('high'), cell('3 hours')],
    ]
    story.append(styled_table(p3_data, [12*mm, 75*mm, 40*mm, 25*mm, 15*mm]))
    story.append(P('<i>Table 6.3 — Phase 3 priorities. P3.1 ships first as a quick morale win (170 TS errors gone in '
                   '1 hour). P3.5 and P3.6 are the largest items and should be done incrementally (one cluster at a '
                   'time) behind re-export shims.</i>', 'Caption'))

    return story


def build_appendix():
    story = []
    story.append(add_heading('7. Appendix — Pattern Reference &amp; Recipes', STYLES['H1'], 0))

    story.append(add_heading('7.1 The Idempotency Recipe (from feedback.ts)', STYLES['H2'], 1))
    story.append(P(
        'The idempotency pattern is already battle-tested in this codebase. The recipe has three steps: add an '
        'optional <code>idempotencyKey</code> arg and a <code>by_idempotency</code> index to the schema; at the '
        'start of the mutation, query the index and return the existing record if a match is found; otherwise '
        'insert with the key. The code snippet below shows the canonical implementation from '
        '<code>convex/feedback.ts</code> that should be replicated for the 5 critical tables identified in Phase 2.'
    ))

    story.append(code('''// 1. Schema (convex/schema.ts)
user_feedback: defineTable({
  // ... existing fields ...
  idempotencyKey: v.optional(v.string()),
}).index("by_idempotency", ["idempotencyKey", "_creationTime"]),

// 2. Mutation (convex/feedback.ts)
export const submitFeedback = mutation({
  args: {
    // ... existing args ...
    idempotencyKey: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    // Dedup check — return existing record if key matches
    if (args.idempotencyKey) {
      const existing = await ctx.db
        .query("user_feedback")
        .withIndex("by_idempotency", q =>
          q.eq("idempotencyKey", args.idempotencyKey))
        .first();
      if (existing) return existing._id;
    }
    // ... normal insert path ...
  },
});

// 3. Client (src/components/forms/FeedbackForm.tsx)
import { v4 as uuidv4 } from 'uuid';
const idempotencyKey = useMemo(() => uuidv4(), []);
await submitFeedback({ /* ...args... */ idempotencyKey });'''))

    story.append(add_heading('7.2 The Soft-Delete Recipe (proposed)', STYLES['H2'], 1))
    story.append(P(
        'The soft-delete pattern extends the existing <code>archive</code> table infrastructure. Instead of calling '
        '<code>db.delete()</code>, the mutation should: snapshot the row to <code>archive</code>, patch the original '
        'row with <code>deletedAt</code>/<code>deletedBy</code>/<code>deletedReason</code>, and update all list '
        'queries to filter out rows where <code>deletedAt</code> is truthy. A helper module '
        '(<code>convex/softDelete.ts</code>) should encapsulate this so the pattern is consistent across modules.'
    ))

    story.append(code('''// 1. Schema additions (per table)
matters: defineTable({
  // ... existing fields ...
  deletedAt: v.optional(v.number()),
  deletedBy: v.optional(v.string()),
  deletedReason: v.optional(v.string()),
}).index("by_firm_deleted", ["firmId", "deletedAt"]),

// 2. Proposed helper (convex/softDelete.ts)
export async function softDelete(
  ctx: QueryCtx,
  table: string,
  id: Id<string>,
  deletedBy: string,
  reason?: string,
) {
  const row = await ctx.db.get(id);
  if (!row || row.deletedAt) return; // idempotent
  await ctx.db.insert("archive", {
    originalTable: table,
    originalId: id,
    snapshot: JSON.stringify(row),
    deletedAt: Date.now(),
    deletedBy,
    reason,
  });
  await ctx.db.patch(id, {
    deletedAt: Date.now(),
    deletedBy,
    deletedReason: reason,
  });
}

// 3. List queries filter out soft-deleted rows
const activeMatters = await ctx.db
  .query("matters")
  .withIndex("by_firm_deleted", q =>
    q.eq("firmId", firmId).eq("deletedAt", undefined))
  .collect();'''))

    story.append(add_heading('7.3 The requireFirmUser Recipe (already proven)', STYLES['H2'], 1))
    story.append(P(
        'The auth gate pattern is already implemented in <code>convex/authHelpers.ts</code>. The defensive fallback '
        'at line 40-56 returns an anonymous context (firmId: \'\', user: null) when userEmail is missing — this is '
        'the legacy-compatibility path that makes the fix safe to add to existing mutations without breaking '
        'callers that have not yet been updated to pass userEmail. To close a portal mutation, prepend the body '
        'with a single line that destructures the auth context.'
    ))

    story.append(code('''// Before (portals.ts:19 — multi-tenant hole)
export const createMaintenanceTicket = mutation({
  args: {
    firmId: v.string(),    // client-supplied — UNVERIFIED
    // ... other args ...
  },
  handler: async (ctx, args) => {
    // directly writes — no auth check
    return await ctx.db.insert("maintenance_tickets", { ... });
  },
});

// After (one-line fix)
export const createMaintenanceTicket = mutation({
  args: {
    firmId: v.string(),
    userEmail: v.optional(v.string()),  // new
    // ... other args ...
  },
  handler: async (ctx, args) => {
    const { firmId } = await requireFirmUser(ctx, args.userEmail, args.firmId);
    // ^ throws if userEmail belongs to a different firm
    return await ctx.db.insert("maintenance_tickets", { firmId, ... });
  },
});'''))

    story.append(add_heading('7.4 Files Modified in This Audit Session', STYLES['H2'], 1))
    story.append(P(
        'The five surgical fixes applied during this audit session are listed below. All changes were verified by a '
        'clean Vite production build (22s) and a TypeScript error reduction from 327 to 315. None of the changes '
        'alter runtime behaviour for legitimate callers; they only add safety (XSS sanitization, submit guards) and '
        'fix pre-existing type-system drift (duplicate imports, missing union literals, nullability).'
    ))

    mod_data = [
        [cell('File', 'TableHeader'), cell('Change', 'TableHeader'), cell('Verified by', 'TableHeader')],
        [cell('src/components/Header.tsx'), cell('Removed duplicate useQuery + api imports (wrong path)'), cell('tsc --noEmit + vite build')],
        [cell('src/services/geminiService.ts'), cell('Added "research" literal to modelPreference union (2 sites)'), cell('tsc --noEmit')],
        [cell('src/utils/capacitor.ts'), cell('Fixed cachedIsNative nullability (use local var)'), cell('tsc --noEmit')],
        [cell('src/components/details/DocumentDetailView.tsx'), cell('Wrapped dangerouslySetInnerHTML in sanitize() + import'), cell('vite build')],
        [cell('src/components/documents/HtmlPagePreview.tsx'), cell('Wrapped 2 dangerouslySetInnerHTML sites in sanitize()'), cell('vite build')],
        [cell('src/components/research/ResearchStudio.tsx'), cell('Wrapped dangerouslySetInnerHTML in sanitize() + import'), cell('vite build')],
        [cell('src/components/TermsAcceptance.tsx'), cell('Added isSubmitting guard + disabled Accept button during await'), cell('vite build')],
    ]
    story.append(styled_table(mod_data, [60*mm, 75*mm, 35*mm]))
    story.append(P('<i>Table 7.1 — Files modified in this audit session. All changes are surgical and verified.</i>', 'Caption'))

    story.append(add_heading('7.5 Audit Methodology', STYLES['H2'], 1))
    story.append(P(
        'This audit was conducted by two parallel exploration agents (one for the Convex backend, one for the React '
        'frontend) using read-only file inspection. Each agent produced a structured report with line-numbered '
        'citations; the findings were cross-referenced against the existing <code>worklog.md</code> entries to '
        'verify which patterns were intentionally applied in previous sessions. The five safe fixes were applied '
        'manually by the main agent and verified by the production build. No files were deleted, no schema was '
        'modified, and no Convex mutations were altered. The full audit transcript is preserved in the conversation '
        'history for future reference.'
    ))

    story.append(P(
        'The methodology prioritized safety above all else. Every recommendation is tagged with an explicit safety '
        'rating (very high / high / medium) and an effort estimate. The phase ordering ensures that no item in a '
        'later phase depends on an item in an earlier phase being shipped first — each item can be deployed '
        'independently. The user should review the roadmap with their engineering team and select items for '
        'implementation based on their own risk tolerance and roadmap priorities.'
    ))

    return story


# ═══════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════

def main():
    output_path = '/home/z/my-project/download/PracticePro_VanCleif_Audit_Report.pdf'

    doc = TocDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=20*mm,
        rightMargin=20*mm,
        topMargin=18*mm,
        bottomMargin=15*mm,
        title='PracticePro Van Cleif Methodology Audit Report',
        author='Super Z (Z.ai)',
        subject='Codebase audit and refactor roadmap',
        creator='Z.ai',
    )

    story = []
    story.extend(build_title_page())
    story.extend(build_toc())
    story.extend(build_executive_summary())
    story.extend(build_methodology_audit())
    story.extend(build_backend_audit())
    story.extend(build_frontend_audit())
    story.extend(build_typescript_health())
    story.extend(build_roadmap())
    story.extend(build_appendix())

    doc.multiBuild(story, onFirstPage=header_footer, onLaterPages=header_footer)
    print(f'Audit report generated: {output_path}')
    print(f'Size: {os.path.getsize(output_path):,} bytes')

if __name__ == '__main__':
    main()
