/**
 * receiptDelivery — regression tests.
 *
 * THE BUG THESE LOCK OUT (2026-09-12, user-reported "receipt could not be
 * generated"): both receipt paths passed messageType:'receipt_issued' to
 * logAutomation, whose Convex validator only accepts the literal union
 * (payment_receipt, rent_reminder, …). The log write was REJECTED after
 * the portal delivery had already succeeded — receipt number never
 * persisted, UI reported failure, and the auto-issue path's stale-closure
 * persist could even revert the manual mark it was receipting.
 */
import { describe, it, expect } from 'vitest';
import {
    RECEIPT_MESSAGE_TYPE,
    buildReceiptLogArgs,
    buildReceiptContent,
    upsertReceiptNumber,
} from '../../src/utils/receiptDelivery';
import type { AutomationMessageType } from '../../src/types';

// The full set the convex/sentry.ts logAutomation validator accepts.
const VALID_MESSAGE_TYPES: AutomationMessageType[] = [
    'custom', 'rent_reminder', 'late_notice', 'payment_receipt',
    'service_charge_alert', 'access_restriction', 'penalty_notice', 'lease_renewal',
];

const baseInput = {
    receiptNumber: 'RC-123456-3',
    chargeTypeLabel: 'Service Charge',
    billingPeriod: 'September 2026',
    tenantName: 'Ada Obi',
    amountPaid: 120000,
    settlementMethod: 'Paid On Time',
    firmId: 'firm-1',
    unitId: 'unit-9',
    senderName: 'Property Manager',
    senderId: 'user-7',
    userEmail: 'pm@firm.ng',
    sessionToken: 'tok-1',
};

describe('RECEIPT_MESSAGE_TYPE — the literal the validator accepts', () => {
    it('is payment_receipt (not the rejected receipt_issued)', () => {
        expect(RECEIPT_MESSAGE_TYPE).toBe('payment_receipt');
        expect(RECEIPT_MESSAGE_TYPE).not.toBe('receipt_issued');
    });

    it('is a member of the logAutomation literal union', () => {
        expect(VALID_MESSAGE_TYPES).toContain(RECEIPT_MESSAGE_TYPE);
    });
});

describe('buildReceiptLogArgs — logAutomation payload', () => {
    it('builds a payload the validator accepts field-for-field', () => {
        const args = buildReceiptLogArgs(baseInput);
        expect(args.messageType).toBe('payment_receipt');
        expect(args.channel).toBe('portal');
        expect(args.status).toBe('sent');
        expect(args.direction).toBe('outbound');
        expect(args.firmId).toBe('firm-1');
        expect(args.unitId).toBe('unit-9');
        expect(args.triggeredBy).toBe('user-7');
        expect(args.recipient).toBe('Ada Obi');
    });

    it('preview + content carry receipt number, charge and amount', () => {
        const args = buildReceiptLogArgs(baseInput);
        expect(args.messagePreview).toContain('RC-123456-3');
        expect(args.messagePreview).toContain('Service Charge');
        expect(args.messageContent).toContain('120,000');
        expect(args.messageContent).toContain('Paid On Time');
    });

    it('formats the amount as ₦ with thousands separators', () => {
        const args = buildReceiptLogArgs({ ...baseInput, amountPaid: 3250000 });
        expect(args.messageContent).toContain('₦3,250,000');
    });

    it('rounds fractional amounts (Brevo/Convex store integers)', () => {
        const args = buildReceiptLogArgs({ ...baseInput, amountPaid: 120000.75 });
        expect(args.messageContent).toContain('₦120,001');
    });
});

describe('buildReceiptContent — resident-facing body', () => {
    it('carries receipt number, amount, date and settlement', () => {
        const content = buildReceiptContent({
            receiptNumber: 'RC-654321-2',
            chargeTypeLabel: 'Minimum Vend',
            billingPeriod: 'August 2026',
            amountPaid: 15000,
            paymentDate: '2026-08-14',
            settlementMethod: 'Paid Late',
            autoGenerated: true,
        });
        expect(content).toContain('RC-654321-2');
        expect(content).toContain('₦15,000');
        expect(content).toContain('2026-08-14');
        expect(content).toContain('Paid Late');
        expect(content).toContain('auto-generated');
    });

    it('includes the coverage note for advance receipts', () => {
        const content = buildReceiptContent({
            receiptNumber: 'RC-999999-4',
            chargeTypeLabel: 'Service Charge',
            billingPeriod: 'September 2026',
            amountPaid: 720000,
            paymentDate: '2026-09-12',
            settlementMethod: 'Advance Payment',
            coverageNote: 'Oct 2026 – Mar 2027 (6 cycles)',
        });
        expect(content).toContain('Covers: Oct 2026 – Mar 2027 (6 cycles)');
    });
});

describe('upsertReceiptNumber — the lost-receipt-number fix', () => {
    it('updates an existing stored row', () => {
        const periods = [{ index: 1, status: 'paid' }, { index: 2, status: 'paid' }];
        const next = upsertReceiptNumber(periods, 2, 'RC-1-2');
        expect(next.find(p => p.index === 2)?.receiptNumber).toBe('RC-1-2');
        expect(next.find(p => p.index === 1)?.receiptNumber).toBeUndefined();
        expect(next).toHaveLength(2);
    });

    it('appends (not drops) when the mark has not been persisted yet', () => {
        // The 2026-09-12 bug: a .map()-only write over an array that did not
        // contain the just-marked period silently dropped the receipt number.
        const periods = [{ index: 1, status: 'paid' }];
        const next = upsertReceiptNumber(periods, 4, 'RC-2-4');
        expect(next.find(p => p.index === 4)?.receiptNumber).toBe('RC-2-4');
        expect(next).toHaveLength(2);
        expect(next.map(p => p.index)).toEqual([1, 4]); // kept sorted
    });

    it('never mutates the input array (stale-closure safety)', () => {
        const periods = [{ index: 1, status: 'paid' }];
        upsertReceiptNumber(periods, 1, 'RC-3-1');
        expect(periods[0].receiptNumber).toBeUndefined();
    });

    it('tolerates null/undefined ledger arrays', () => {
        const next = upsertReceiptNumber(undefined, 3, 'RC-4-3');
        expect(next.find(p => p.index === 3)?.receiptNumber).toBe('RC-4-3');
    });
});
